import os
import json
import uuid
import random
from datetime import date, datetime, timedelta, timezone
from typing import Dict, Any, List, Optional
from app.providers.aa.aa_provider import BaseAAProvider

class MockAAProvider(BaseAAProvider):
    """
    Mock / Sandbox Account Aggregator Provider conforming to Sahamati AA standards.
    Simulates FIU-AA consent lifecycle and authorized bank data retrieval.
    Clearly designated for Demo / Hackathon environments (DEMO MODE).
    """

    MOCK_ACCOUNTS = [
        {
            "account_id": "acc_hdfc_4521",
            "bank_name": "HDFC Bank",
            "account_mask": "•••• 4521",
            "account_type": "SAVINGS",
            "fip_id": "FIP-HDFC-01",
            "fip_name": "HDFC Bank Financial Information Provider",
            "balance_indicative": 32400.00,
            "currency": "INR",
            "is_linked": True,
            "is_selected": True
        },
        {
            "account_id": "acc_sbi_8912",
            "bank_name": "State Bank of India",
            "account_mask": "•••• 8912",
            "account_type": "SAVINGS",
            "fip_id": "FIP-SBI-01",
            "fip_name": "SBI Financial Information Provider",
            "balance_indicative": 18500.00,
            "currency": "INR",
            "is_linked": True,
            "is_selected": True
        },
        {
            "account_id": "acc_icici_3318",
            "bank_name": "ICICI Bank",
            "account_mask": "•••• 3318",
            "account_type": "SAVINGS",
            "fip_id": "FIP-ICICI-01",
            "fip_name": "ICICI Bank Financial Information Provider",
            "balance_indicative": 54200.00,
            "currency": "INR",
            "is_linked": True,
            "is_selected": False
        },
        {
            "account_id": "acc_axis_7742",
            "bank_name": "Axis Bank",
            "account_mask": "•••• 7742",
            "account_type": "SAVINGS",
            "fip_id": "FIP-AXIS-01",
            "fip_name": "Axis Bank Financial Information Provider",
            "balance_indicative": 28900.00,
            "currency": "INR",
            "is_linked": True,
            "is_selected": False
        },
        {
            "account_id": "acc_kotak_1184",
            "bank_name": "Kotak Mahindra Bank",
            "account_mask": "•••• 1184",
            "account_type": "SAVINGS",
            "fip_id": "FIP-KOTAK-01",
            "fip_name": "Kotak Mahindra Bank Financial Information Provider",
            "balance_indicative": 15400.00,
            "currency": "INR",
            "is_linked": True,
            "is_selected": False
        }
    ]

    def __init__(self):
        self._consents: Dict[str, Dict[str, Any]] = {}
        # Locate mock transactions store file if generated by seed script
        curr_dir = os.path.dirname(os.path.abspath(__file__))
        backend_dir = os.path.dirname(os.path.dirname(curr_dir))
        self.mock_store_path = os.path.join(backend_dir, "app", "scripts", "mock_transactions_data.json")

    def _load_mock_tx_store(self) -> Dict[str, Any]:
        if os.path.exists(self.mock_store_path):
            try:
                with open(self.mock_store_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass
        return {}

    def create_consent_request(
        self,
        worker_id: str,
        purpose: str,
        data_types: List[str],
        date_range: Dict[str, Optional[date]]
    ) -> Dict[str, Any]:
        consent_id = f"AA-REQ-{uuid.uuid4().hex[:12].upper()}"
        start_d = date_range.get("start_date")
        end_d = date_range.get("end_date")

        consent_artifact = {
            "consent_id": consent_id,
            "worker_id": worker_id,
            "provider": "Mock Account Aggregator (Sahamati Sandbox - DEMO MODE)",
            "purpose": purpose or "Income verification only",
            "data_types": data_types or ["TRANSACTIONS", "PROFILE"],
            "start_date": start_d.isoformat() if start_d else (date.today() - timedelta(days=365)).isoformat(),
            "end_date": end_d.isoformat() if end_d else date.today().isoformat(),
            "consent_status": "ACTIVE",
            "consent_version": "v1.0",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "expires_at": (datetime.now(timezone.utc) + timedelta(days=90)).isoformat(),
            "is_demo": True
        }
        self._consents[consent_id] = consent_artifact
        return consent_artifact

    def fetch_linked_accounts(self, worker_id: str) -> List[Dict[str, Any]]:
        """
        Dynamically returns linked bank accounts for the worker.
        All account numbers are strictly masked (e.g. •••• 4521).
        """
        try:
            from app.db.session import SessionLocal
            from app.models.financial_account import FinancialAccount
            db = SessionLocal()
            try:
                db_accs = db.query(FinancialAccount).filter(FinancialAccount.worker_id == worker_id).all()
                if db_accs:
                    return [
                        {
                            "account_id": acc.id,
                            "bank_name": acc.bank_name,
                            "account_mask": acc.account_mask,
                            "account_type": acc.account_type,
                            "fip_id": acc.fip_id,
                            "fip_name": acc.fip_name or f"{acc.bank_name} Information Provider",
                            "balance_indicative": acc.balance_indicative,
                            "currency": acc.currency,
                            "is_linked": acc.is_linked,
                            "is_selected": acc.is_selected
                        }
                        for acc in db_accs
                    ]
            finally:
                db.close()
        except Exception:
            pass

        # Default fallback accounts
        return [dict(acc) for acc in self.MOCK_ACCOUNTS]

    def fetch_financial_data(
        self,
        consent_id: str,
        account_ids: List[str],
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        worker_id: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Retrieves 12-month synthetic transaction history for authorized bank accounts.
        Pulls from seeded synthetic data store when available, or synthesizes on-demand.
        """
        today = end_date or date.today()
        start = start_date or (today - timedelta(days=365))

        # 1. Try to load from persisted mock data store
        store = self._load_mock_tx_store()
        if worker_id and worker_id in store:
            user_txs = store[worker_id]
            # Filter by date and account if requested
            filtered = []
            for tx in user_txs:
                t_date = date.fromisoformat(tx["transaction_date"])
                if start <= t_date <= today:
                    # If accounts specified, match either by mask or account_id
                    if account_ids and len(account_ids) > 0:
                        acc_mask = tx.get("account_mask", "")
                        acc_id = tx.get("account_id", "")
                        if not any(aid in (acc_mask, acc_id) for aid in account_ids):
                            # Try matching account by bank
                            pass
                    filtered.append(tx)
            if filtered:
                return filtered

        # 2. Fallback synthesis across 12 months
        transactions: List[Dict[str, Any]] = []
        rng = random.Random(42)

        # Fictional & standard gig sources
        gig_sources = [
            {"name": "QuickRide", "desc": "UPI/CR/QUICKRIDE TECHNOLOGIES/WEEKLY DRIVER PAYOUT", "min_amt": 3200, "max_amt": 6800},
            {"name": "FoodDash", "desc": "UPI/CR/FOODDASH MEDIA PVT LTD/WEEKLY SETTLEMENT", "min_amt": 2800, "max_amt": 5400},
            {"name": "UrbanMove", "desc": "NEFT CR-URBANMOVE CABS-DISBURSEMENT", "min_amt": 4100, "max_amt": 7500},
            {"name": "ParcelGo", "desc": "IMPS CR-PARCELGO LOGISTICS-PAYOUT", "min_amt": 2100, "max_amt": 4200},
            {"name": "TaskKart", "desc": "UPI/CR/TASKKART SERVICES/PARTNER INCENTIVE", "min_amt": 1900, "max_amt": 3800},
            {"name": "Uber", "desc": "UPI/CR/UBER INDIA SYSTEMS/WEEKLY DRIVER PAYOUT", "min_amt": 3500, "max_amt": 7200},
            {"name": "Zomato", "desc": "UPI/CR/ZOMATO LIMITED/PARTNER EARNINGS", "min_amt": 3000, "max_amt": 6500}
        ]

        non_gig_sources = [
            {"desc": "UPI/CR/FAMILY P2P TRANSFER", "type": "CREDIT", "min": 500, "max": 2500},
            {"desc": "NEFT CR/EARLYSALARY LENDING/PERSONAL LOAN", "type": "CREDIT", "min": 25000, "max": 50000},
            {"desc": "BY CASH DEPOSIT AT BRANCH", "type": "CREDIT", "min": 5000, "max": 10000},
            {"desc": "INTERNAL TRANSFER: HDFC -> SBI", "type": "CREDIT", "min": 4000, "max": 8000},
            {"desc": "UPI/CR/FOODDASH REFUND", "type": "CREDIT", "min": 450, "max": 900},
            {"desc": "POS DEBIT/HPCL PETROL PUMP", "type": "DEBIT", "min": 400, "max": 950},
            {"desc": "UPI/DR/SWIGGY INSTAMART GROCERIES", "type": "DEBIT", "min": 350, "max": 1200},
            {"desc": "ATM WDL/SBI ATM CASH", "type": "DEBIT", "min": 1000, "max": 4000}
        ]

        curr = start
        while curr <= today:
            # Regular weekly disbursements
            if curr.weekday() in (1, 4):
                g_template = rng.choice(gig_sources)
                amt = round(rng.uniform(g_template["min_amt"], g_template["max_amt"]), 2)
                transactions.append({
                    "id": f"tx_mock_{uuid.uuid4().hex[:10]}",
                    "account_mask": "•••• 4521",
                    "bank_name": "HDFC Bank",
                    "transaction_date": curr.isoformat(),
                    "transaction_type": "CREDIT",
                    "amount": amt,
                    "description": g_template["desc"],
                    "source": "HDFC Bank (•••• 4521)",
                    "reference_id": f"REF{curr.strftime('%Y%m%d')}{rng.randint(1000, 9999)}",
                    "is_demo": True
                })

            if rng.random() < 0.40:
                ng_template = rng.choice(non_gig_sources)
                amt = round(rng.uniform(ng_template["min"], ng_template["max"]), 2)
                transactions.append({
                    "id": f"tx_mock_{uuid.uuid4().hex[:10]}",
                    "account_mask": "•••• 4521",
                    "bank_name": "HDFC Bank",
                    "transaction_date": curr.isoformat(),
                    "transaction_type": ng_template["type"],
                    "amount": amt,
                    "description": ng_template["desc"],
                    "source": "HDFC Bank (•••• 4521)",
                    "reference_id": f"REF{curr.strftime('%Y%m%d')}{rng.randint(1000, 9999)}",
                    "is_demo": True
                })

            curr += timedelta(days=1)

        transactions.sort(key=lambda x: x["transaction_date"], reverse=True)
        return transactions
